#!/bin/bash
python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 11 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 2 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 17 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 2 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 25 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 2 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 37 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 2 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 49 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 2 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 3 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 4 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 7 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 4 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 11 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 4 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 17 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 4 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 37 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 4 --deactivate_lrscheduler

python main.py --dynsys 2DCyl --lr 5e-5 --nepochs 2000 --train_size 0.99 --info lr5e-5 --nhu 40 --seq_len 49 --data_dir Data/2DCylinder/cyl_data_10_2.npy --exp_dir Trained_Models/2DCyl_Num_seqlentest_ts10_2_localtest --num_obs 4 --deactivate_lrscheduler













